entities:
  Instrument:
    description: "Financial instruments"
    specific_types:
      - Stock
      - Option
      - Future
      - Bond
    id_types:
      InstrumentId:
        inputs:
          - id: "instrumentId"
            label: "Instrument ID"
            kind: "text"
            required: true
            validation: "^[A-Z0-9]{6,12}$"
      RIC:
        inputs:
          - id: "ric"
            label: "RIC"
            kind: "text"
            required: true
      ISIN:
        inputs:
          - id: "isin"
            label: "ISIN"
            kind: "text"
            required: true
      Economics:
        inputs:
          - id: "underlyingInstrumentId"
            label: "Underlying Instrument ID"
            kind: "text"
            required: true
          - id: "strike"
            label: "Strike"
            kind: "number"
            required: true
          - id: "contractSize"
            label: "Contract Size"
            kind: "number"
            required: false
          - id: "expirationDate"
            label: "Expiration Date"
            kind: "date"
            required: true
          - id: "callOrPut"
            label: "Call or Put"
            kind: "select"
            options: ["Call", "Put"]
            required: true

  Account:
    description: "Trading and settlement accounts"
    specific_types:
      - Account
      - ClientAccount
    id_types:
      CAID:
        inputs:
          - id: "caid"
            label: "CAID"
            kind: "text"
            required: true
      CASSII:
        inputs:
          - id: "cassii"
            label: "CASSII"
            kind: "text"
            required: true
      SPN:
        inputs:
          - id: "spn"
            label: "SPN"
            kind: "text"
            required: true

  Client:
    description: "Client entities"
    specific_types:
      - Client
    id_types:
      ECI: # JPM Party 1.0 Identifier
        inputs:
          - id: "eci"
            label: "ECI"
            kind: "text"
            required: true
      SPN:
        inputs:
          - id: "spn"
            label: "SPN"
            kind: "text"
            required: true
      EPI: # JPM Party 2.0 Identifier
        inputs:
          - id: "epi"
            label: "EPI"
            kind: "text"
            required: true

# Specific Entity Types (actual nodes in graph)
specific_entities:
  Stock:
    parent_type: "Instrument"
    display_config:
      title_line1_field: "instrument_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "instrumentId"
          label: "Instrument ID"
        - field: "isin"
          label: "ISIN"
        - field: "primaryTradingLine"
          label: "Primary Trading Line"
        - field: "sector"
          label: "Sector"
    data_source:
      provider: "InstrumentDataProvider"
      method: "get_stock_by_id"
      cache_ttl: 300
    
  Option:
    parent_type: "Instrument"
    display_config:
      title_line1_field: "instrument_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "instrumentId"
          label: "Instrument ID"
        - field: "optionType"
          label: "Option Type"
        - field: "strike"
          label: "Strike"
        - field: "expirationDate"
          label: "Expiration Date"
        - field: "underlyingInstrumentId"
          label: "Underlying"
    data_source:
      provider: "InstrumentDataProvider"
      method: "get_option_by_id"
      cache_ttl: 180

  Future:
    parent_type: "Instrument"
    display_config:
      title_line1_field: "instrument_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "instrumentId"
          label: "Instrument ID"
        - field: "underlyingAsset"
          label: "Underlying Asset"
        - field: "expirationDate"
          label: "Expiration Date"
        - field: "contractSize"
          label: "Contract Size"
        - field: "settlementType"
          label: "Settlement Type"
    data_source:
      provider: "InstrumentDataProvider"
      method: "get_future_by_id"
      cache_ttl: 240

  Bond:
    parent_type: "Instrument"
    display_config:
      title_line1_field: "instrument_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "instrumentId"
          label: "Instrument ID"
        - field: "isin"
          label: "ISIN"
        - field: "couponRate"
          label: "Coupon Rate"
        - field: "maturityDate"
          label: "Maturity Date"
        - field: "creditRating"
          label: "Credit Rating"
    data_source:
      provider: "InstrumentDataProvider"
      method: "get_bond_by_id"
      cache_ttl: 600

  Listing:
    parent_type: null
    display_config:
      title_line1_field: "listing_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "tradingLineId"
          label: "Trading Line ID"
        - field: "ric"
          label: "RIC"
        - field: "bloombergTicker"
          label: "BBG Ticker"
        - field: "exchangeId"
          label: "Exchange"
    data_source:
      provider: "ListingDataProvider"
      method: "get_listing_by_id"
      cache_ttl: 600

  Exchange:
    parent_type: null
    display_config:
      title_line1_field: "exchange_code"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "settlementDays"
          label: "Settlement Days"
        - field: "venueId"
          label: "Venue ID"
        - field: "currency"
          label: "Currency"
    data_source:
      provider: "ExchangeDataProvider"
      method: "get_exchange_by_id"
      cache_ttl: 3600

  InstrumentParty:
    parent_type: null
    display_config:
      title_line1_field: "party_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "instrumentPartyId"
          label: "IPARTY"
        - field: "eci"
          label: "ECI"
        - field: "entityType"
          label: "Entity Type"
    data_source:
      provider: "PartyDataProvider"
      method: "get_instrument_party_by_id"
      cache_ttl: 1800

  Client:
    parent_type: null
    display_config:
      title_line1_field: "client_type"
      title_line2_field: "name"
      status_field: "status"
      additional_fields:
        - field: "clientId"
          label: "Client ID"
        - field: "eci"
          label: "ECI"
        - field: "lei"
          label: "LEI"
        - field: "clientType"
          label: "Client Type"
    data_source:
      provider: "PartyDataProvider"
      method: "get_client_by_id"
      cache_ttl: 1800
